services:
  master:
    build: .
    container_name: mr-master
    command:
      - "--mode=master"
      - "--min_workers=3"
      - "/data/doc1.txt"
      - "/data/doc2.txt"
      - "/data/doc3.txt"
      - "/data/doc4.txt"
      - "/data/doc5.txt"
    volumes:
      - ./test-inputs:/data:ro
      - ./output:/workdir
    environment:
      - LOG_FORMAT=json
    working_dir: /workdir
    ports:
      - "50051:50051"

  worker-1:
    build: .
    container_name: mr-worker-1
    command: ["--mode=worker", "--addr=worker-1:50052", "--master_addr=master:50051"]
    volumes:
      - ./test-inputs:/data:ro
      - worker-1-workdir:/workdir
    environment:
      - LOG_FORMAT=json
      - SIMULATE_SLOW_MAP=8s
      - SIMULATE_SLOW_REDUCE=5s
    working_dir: /workdir
    depends_on:
      - master

  worker-2:
    build: .
    container_name: mr-worker-2
    command: ["--mode=worker", "--addr=worker-2:50052", "--master_addr=master:50051"]
    volumes:
      - ./test-inputs:/data:ro
      - worker-2-workdir:/workdir
    environment:
      - LOG_FORMAT=json
      - SIMULATE_SLOW_MAP=8s
      - SIMULATE_SLOW_REDUCE=5s
    working_dir: /workdir
    depends_on:
      - master

  worker-3:
    build: .
    container_name: mr-worker-3
    command: ["--mode=worker", "--addr=worker-3:50052", "--master_addr=master:50051"]
    volumes:
      - ./test-inputs:/data:ro
      - worker-3-workdir:/workdir
    environment:
      - LOG_FORMAT=json
      - SIMULATE_SLOW_MAP=8s
      - SIMULATE_SLOW_REDUCE=5s
    working_dir: /workdir
    depends_on:
      - master

volumes:
  worker-1-workdir:
  worker-2-workdir:
  worker-3-workdir:
