global:
  scrape_interval: 1s

scrape_configs:
  - job_name: mapreduce
    static_configs:
      - targets:
        - master:9090
        - worker-1:9090
        - worker-2:9090
        - worker-3:9090