// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mapreduce.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_Type int32

const (
	Task_IDLE     Task_Type = 0
	Task_MAP      Task_Type = 1
	Task_REDUCE   Task_Type = 2
	Task_SHUTDOWN Task_Type = 3
)

// Enum value maps for Task_Type.
var (
	Task_Type_name = map[int32]string{
		0: "IDLE",
		1: "MAP",
		2: "REDUCE",
		3: "SHUTDOWN",
	}
	Task_Type_value = map[string]int32{
		"IDLE":     0,
		"MAP":      1,
		"REDUCE":   2,
		"SHUTDOWN": 3,
	}
)

func (x Task_Type) Enum() *Task_Type {
	p := new(Task_Type)
	*p = x
	return p
}

func (x Task_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[0].Descriptor()
}

func (Task_Type) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[0]
}

func (x Task_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Type.Descriptor instead.
func (Task_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3, 0}
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{1}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr    string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Task_Type              `protobuf:"varint,1,opt,name=type,proto3,enum=Task_Type" json:"type,omitempty"`
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`       // map: путь к фалу
	Partition     int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`                    // reduce: номер партиции
	SpillAddrs    []string               `protobuf:"bytes,5,rep,name=spill_addrs,json=spillAddrs,proto3" json:"spill_addrs,omitempty"` // reduce: адреса воркеров с нужными файлами
	NumPartitions int32                  `protobuf:"varint,6,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetType() Task_Type {
	if x != nil {
		return x.Type
	}
	return Task_IDLE
}

func (x *Task) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Task) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Task) GetSpillAddrs() []string {
	if x != nil {
		return x.SpillAddrs
	}
	return nil
}

func (x *Task) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

type TaskDone struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr           string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	TaskId               int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NumCreatedPartitions int32                  `protobuf:"varint,3,opt,name=num_created_partitions,json=numCreatedPartitions,proto3" json:"num_created_partitions,omitempty"` // map : сколько партиций создалось
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskDone) Reset() {
	*x = TaskDone{}
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDone) ProtoMessage() {}

func (x *TaskDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDone.ProtoReflect.Descriptor instead.
func (*TaskDone) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *TaskDone) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

func (x *TaskDone) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskDone) GetNumCreatedPartitions() int32 {
	if x != nil {
		return x.NumCreatedPartitions
	}
	return 0
}

type FetchSpillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSpillRequest) Reset() {
	*x = FetchSpillRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSpillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSpillRequest) ProtoMessage() {}

func (x *FetchSpillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSpillRequest.ProtoReflect.Descriptor instead.
func (*FetchSpillRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *FetchSpillRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type FetchResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResultRequest) Reset() {
	*x = FetchResultRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResultRequest) ProtoMessage() {}

func (x *FetchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResultRequest.ProtoReflect.Descriptor instead.
func (*FetchResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *FetchResultRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr    string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

type SpillChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpillChunk) Reset() {
	*x = SpillChunk{}
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpillChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpillChunk) ProtoMessage() {}

func (x *SpillChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpillChunk.ProtoReflect.Descriptor instead.
func (*SpillChunk) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{8}
}

func (x *SpillChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_mapreduce_proto protoreflect.FileDescriptor

const file_proto_mapreduce_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mapreduce.proto\" \n" +
	"\n" +
	"WorkerInfo\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\x05\n" +
	"\x03Ack\".\n" +
	"\vTaskRequest\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\"\xf7\x01\n" +
	"\x04Task\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".Task.TypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\x12\x1f\n" +
	"\vspill_addrs\x18\x05 \x03(\tR\n" +
	"spillAddrs\x12%\n" +
	"\x0enum_partitions\x18\x06 \x01(\x05R\rnumPartitions\"3\n" +
	"\x04Type\x12\b\n" +
	"\x04IDLE\x10\x00\x12\a\n" +
	"\x03MAP\x10\x01\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x02\x12\f\n" +
	"\bSHUTDOWN\x10\x03\"z\n" +
	"\bTaskDone\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x124\n" +
	"\x16num_created_partitions\x18\x03 \x01(\x05R\x14numCreatedPartitions\"1\n" +
	"\x11FetchSpillRequest\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\"2\n" +
	"\x12FetchResultRequest\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\" \n" +
	"\n" +
	"SpillChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x96\x01\n" +
	"\x06Master\x12#\n" +
	"\x0eRegisterWorker\x12\v.WorkerInfo\x1a\x04.Ack\x12\"\n" +
	"\vRequestTask\x12\f.TaskRequest\x1a\x05.Task\x12\x1d\n" +
	"\n" +
	"ReportDone\x12\t.TaskDone\x1a\x04.Ack\x12$\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x04.Ack2l\n" +
	"\x06Worker\x12/\n" +
	"\n" +
	"FetchSpill\x12\x12.FetchSpillRequest\x1a\v.SpillChunk0\x01\x121\n" +
	"\vFetchResult\x12\x13.FetchResultRequest\x1a\v.SpillChunk0\x01B\x11Z\x0fmapreduce/protob\x06proto3"

var (
	file_proto_mapreduce_proto_rawDescOnce sync.Once
	file_proto_mapreduce_proto_rawDescData []byte
)

func file_proto_mapreduce_proto_rawDescGZIP() []byte {
	file_proto_mapreduce_proto_rawDescOnce.Do(func() {
		file_proto_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)))
	})
	return file_proto_mapreduce_proto_rawDescData
}

var file_proto_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mapreduce_proto_goTypes = []any{
	(Task_Type)(0),             // 0: Task.Type
	(*WorkerInfo)(nil),         // 1: WorkerInfo
	(*Ack)(nil),                // 2: Ack
	(*TaskRequest)(nil),        // 3: TaskRequest
	(*Task)(nil),               // 4: Task
	(*TaskDone)(nil),           // 5: TaskDone
	(*FetchSpillRequest)(nil),  // 6: FetchSpillRequest
	(*FetchResultRequest)(nil), // 7: FetchResultRequest
	(*HeartbeatRequest)(nil),   // 8: HeartbeatRequest
	(*SpillChunk)(nil),         // 9: SpillChunk
}
var file_proto_mapreduce_proto_depIdxs = []int32{
	0, // 0: Task.type:type_name -> Task.Type
	1, // 1: Master.RegisterWorker:input_type -> WorkerInfo
	3, // 2: Master.RequestTask:input_type -> TaskRequest
	5, // 3: Master.ReportDone:input_type -> TaskDone
	8, // 4: Master.Heartbeat:input_type -> HeartbeatRequest
	6, // 5: Worker.FetchSpill:input_type -> FetchSpillRequest
	7, // 6: Worker.FetchResult:input_type -> FetchResultRequest
	2, // 7: Master.RegisterWorker:output_type -> Ack
	4, // 8: Master.RequestTask:output_type -> Task
	2, // 9: Master.ReportDone:output_type -> Ack
	2, // 10: Master.Heartbeat:output_type -> Ack
	9, // 11: Worker.FetchSpill:output_type -> SpillChunk
	9, // 12: Worker.FetchResult:output_type -> SpillChunk
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mapreduce_proto_init() }
func file_proto_mapreduce_proto_init() {
	if File_proto_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_mapreduce_proto_goTypes,
		DependencyIndexes: file_proto_mapreduce_proto_depIdxs,
		EnumInfos:         file_proto_mapreduce_proto_enumTypes,
		MessageInfos:      file_proto_mapreduce_proto_msgTypes,
	}.Build()
	File_proto_mapreduce_proto = out.File
	file_proto_mapreduce_proto_goTypes = nil
	file_proto_mapreduce_proto_depIdxs = nil
}
