// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mapreduce.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_Type int32

const (
	Task_IDLE     Task_Type = 0
	Task_MAP      Task_Type = 1
	Task_REDUCE   Task_Type = 2
	Task_SHUTDOWN Task_Type = 3
)

// Enum value maps for Task_Type.
var (
	Task_Type_name = map[int32]string{
		0: "IDLE",
		1: "MAP",
		2: "REDUCE",
		3: "SHUTDOWN",
	}
	Task_Type_value = map[string]int32{
		"IDLE":     0,
		"MAP":      1,
		"REDUCE":   2,
		"SHUTDOWN": 3,
	}
)

func (x Task_Type) Enum() *Task_Type {
	p := new(Task_Type)
	*p = x
	return p
}

func (x Task_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[0].Descriptor()
}

func (Task_Type) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[0]
}

func (x Task_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Type.Descriptor instead.
func (Task_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3, 0}
}

type GetJobStatusResponse_Status int32

const (
	GetJobStatusResponse_UNKNOWN GetJobStatusResponse_Status = 0
	GetJobStatusResponse_RUNNING GetJobStatusResponse_Status = 1
	GetJobStatusResponse_DONE    GetJobStatusResponse_Status = 2
	GetJobStatusResponse_FAILED  GetJobStatusResponse_Status = 3
)

// Enum value maps for GetJobStatusResponse_Status.
var (
	GetJobStatusResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
		2: "DONE",
		3: "FAILED",
	}
	GetJobStatusResponse_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"RUNNING": 1,
		"DONE":    2,
		"FAILED":  3,
	}
)

func (x GetJobStatusResponse_Status) Enum() *GetJobStatusResponse_Status {
	p := new(GetJobStatusResponse_Status)
	*p = x
	return p
}

func (x GetJobStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJobStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[1].Descriptor()
}

func (GetJobStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[1]
}

func (x GetJobStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJobStatusResponse_Status.Descriptor instead.
func (GetJobStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{9, 0}
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{1}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr    string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Task_Type              `protobuf:"varint,1,opt,name=type,proto3,enum=Task_Type" json:"type,omitempty"`
	TaskId        int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Partition     int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	NumPartitions int32                  `protobuf:"varint,6,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	JobId         int32                  `protobuf:"varint,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetType() Task_Type {
	if x != nil {
		return x.Type
	}
	return Task_IDLE
}

func (x *Task) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Task) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Task) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *Task) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type TaskDone struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr           string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	TaskId               int32                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NumCreatedPartitions int32                  `protobuf:"varint,3,opt,name=num_created_partitions,json=numCreatedPartitions,proto3" json:"num_created_partitions,omitempty"`
	JobId                int32                  `protobuf:"varint,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Failed               bool                   `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskDone) Reset() {
	*x = TaskDone{}
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDone) ProtoMessage() {}

func (x *TaskDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDone.ProtoReflect.Descriptor instead.
func (*TaskDone) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *TaskDone) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

func (x *TaskDone) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskDone) GetNumCreatedPartitions() int32 {
	if x != nil {
		return x.NumCreatedPartitions
	}
	return 0
}

func (x *TaskDone) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *TaskDone) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *TaskDone) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerAddr    string                 `protobuf:"bytes,1,opt,name=worker_addr,json=workerAddr,proto3" json:"worker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePaths     []string               `protobuf:"bytes,1,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitJobRequest) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitJobResponse) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobStatusRequest) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        GetJobStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=GetJobStatusResponse_Status" json:"status,omitempty"`
	IndexPath     string                      `protobuf:"bytes,2,opt,name=index_path,json=indexPath,proto3" json:"index_path,omitempty"` // set when status = DONE
	ErrorMessage  string                      `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobStatusResponse) GetStatus() GetJobStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetJobStatusResponse_UNKNOWN
}

func (x *GetJobStatusResponse) GetIndexPath() string {
	if x != nil {
		return x.IndexPath
	}
	return ""
}

func (x *GetJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_mapreduce_proto protoreflect.FileDescriptor

const file_proto_mapreduce_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mapreduce.proto\" \n" +
	"\n" +
	"WorkerInfo\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\x05\n" +
	"\x03Ack\".\n" +
	"\vTaskRequest\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\"\xf3\x01\n" +
	"\x04Task\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".Task.TypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\x12%\n" +
	"\x0enum_partitions\x18\x06 \x01(\x05R\rnumPartitions\x12\x15\n" +
	"\x06job_id\x18\a \x01(\x05R\x05jobId\"3\n" +
	"\x04Type\x12\b\n" +
	"\x04IDLE\x10\x00\x12\a\n" +
	"\x03MAP\x10\x01\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x02\x12\f\n" +
	"\bSHUTDOWN\x10\x03J\x04\b\x05\x10\x06\"\xce\x01\n" +
	"\bTaskDone\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x05R\x06taskId\x124\n" +
	"\x16num_created_partitions\x18\x03 \x01(\x05R\x14numCreatedPartitions\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\x05R\x05jobId\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\bR\x06failed\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vworker_addr\x18\x01 \x01(\tR\n" +
	"workerAddr\"1\n" +
	"\x10SubmitJobRequest\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x01 \x03(\tR\tfilePaths\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x05R\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x05R\x05jobId\"\xca\x01\n" +
	"\x14GetJobStatusResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.GetJobStatusResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"index_path\x18\x02 \x01(\tR\tindexPath\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"8\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\x87\x02\n" +
	"\x06Master\x12#\n" +
	"\x0eRegisterWorker\x12\v.WorkerInfo\x1a\x04.Ack\x12\"\n" +
	"\vRequestTask\x12\f.TaskRequest\x1a\x05.Task\x12\x1d\n" +
	"\n" +
	"ReportDone\x12\t.TaskDone\x1a\x04.Ack\x12$\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x04.Ack\x122\n" +
	"\tSubmitJob\x12\x11.SubmitJobRequest\x1a\x12.SubmitJobResponse\x12;\n" +
	"\fGetJobStatus\x12\x14.GetJobStatusRequest\x1a\x15.GetJobStatusResponseB\x11Z\x0fmapreduce/protob\x06proto3"

var (
	file_proto_mapreduce_proto_rawDescOnce sync.Once
	file_proto_mapreduce_proto_rawDescData []byte
)

func file_proto_mapreduce_proto_rawDescGZIP() []byte {
	file_proto_mapreduce_proto_rawDescOnce.Do(func() {
		file_proto_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)))
	})
	return file_proto_mapreduce_proto_rawDescData
}

var file_proto_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_mapreduce_proto_goTypes = []any{
	(Task_Type)(0),                   // 0: Task.Type
	(GetJobStatusResponse_Status)(0), // 1: GetJobStatusResponse.Status
	(*WorkerInfo)(nil),               // 2: WorkerInfo
	(*Ack)(nil),                      // 3: Ack
	(*TaskRequest)(nil),              // 4: TaskRequest
	(*Task)(nil),                     // 5: Task
	(*TaskDone)(nil),                 // 6: TaskDone
	(*HeartbeatRequest)(nil),         // 7: HeartbeatRequest
	(*SubmitJobRequest)(nil),         // 8: SubmitJobRequest
	(*SubmitJobResponse)(nil),        // 9: SubmitJobResponse
	(*GetJobStatusRequest)(nil),      // 10: GetJobStatusRequest
	(*GetJobStatusResponse)(nil),     // 11: GetJobStatusResponse
}
var file_proto_mapreduce_proto_depIdxs = []int32{
	0,  // 0: Task.type:type_name -> Task.Type
	1,  // 1: GetJobStatusResponse.status:type_name -> GetJobStatusResponse.Status
	2,  // 2: Master.RegisterWorker:input_type -> WorkerInfo
	4,  // 3: Master.RequestTask:input_type -> TaskRequest
	6,  // 4: Master.ReportDone:input_type -> TaskDone
	7,  // 5: Master.Heartbeat:input_type -> HeartbeatRequest
	8,  // 6: Master.SubmitJob:input_type -> SubmitJobRequest
	10, // 7: Master.GetJobStatus:input_type -> GetJobStatusRequest
	3,  // 8: Master.RegisterWorker:output_type -> Ack
	5,  // 9: Master.RequestTask:output_type -> Task
	3,  // 10: Master.ReportDone:output_type -> Ack
	3,  // 11: Master.Heartbeat:output_type -> Ack
	9,  // 12: Master.SubmitJob:output_type -> SubmitJobResponse
	11, // 13: Master.GetJobStatus:output_type -> GetJobStatusResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mapreduce_proto_init() }
func file_proto_mapreduce_proto_init() {
	if File_proto_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mapreduce_proto_goTypes,
		DependencyIndexes: file_proto_mapreduce_proto_depIdxs,
		EnumInfos:         file_proto_mapreduce_proto_enumTypes,
		MessageInfos:      file_proto_mapreduce_proto_msgTypes,
	}.Build()
	File_proto_mapreduce_proto = out.File
	file_proto_mapreduce_proto_goTypes = nil
	file_proto_mapreduce_proto_depIdxs = nil
}
